### ISSUE TITLE
Recipe List API (Main)

### ISSUE THREAD

**Issue by UTkzhang** [ECE444-2020Fall/project1-plateup-group5-pyromaniacs#16]
We must be able to query the recipe database based on a bunch of criteria (filters, etc) and return a list of recipes to the frontend. 

Input:
keyword (ingredients, dish name, etc) or no input (randomize selection)
limit (how many)
page (which page)

Process:
call function IRsearch to get the recipe ids back
query recipe database with recipe ids to retrieve recipe objects
return the objects in the right format

Output:
list of recipes, json set up something like
{
recipes: [
recipe1{},
recipe2{},
]
}

Acceptance criteria
Postman call to endpoint returns the expected json for the user

endpoint: /recipes?userid=xxx&filters=xxx&limit=x&page=x

**Comment by shadow-blade-X** [comment]
Done with the pull request #36
