### ISSUE TITLE
Filter recipes in various ways

### ISSUE THREAD

**Issue by eanile** [ECE444-2020Fall/project1-plateup-group5-pyromaniacs#5]
We should be able to filter recipes by things such as cooking time and recipe cost. Frontend need not be implemented: analyzing a list of recipes returned from the filtering operation to determine if the list changes in an expected way should suffice.

Another user story regarding filtering concerns recipe complexity, though this may be non-trivial to implement and is thus left out of the acceptance criteria. However, if it isn't too hard, implementing this is desired as well as all three of the aforementioned filtering methods covers all of Epic 1 Theme 2's user stories.

Acceptance Criteria
- List of recipes searched by the user can be filtered by cooking time/recipe cost

**Comment by shadow-blade-X** [comment]
This issue is done in pull request #36
