### ISSUE TITLE
Filter by ingredients in my grocery cart

### ISSUE THREAD

**Issue by fcpranav** [ECE444-2020Fall/project1-plateup-group5-pyromaniacs#75]
The filters screen currently has a toggle for "Show only recipes you have ingredients for". This toggle currently does not do anything. Once the grocery cart is fully developed, we can finish this functionality. Most of the work for this is on the backend. Ensure the frontend functionality is completed and this filter is applied correctly.

AC:
- Ensure the filter is being applied when the user is browsing recipes

**Comment by eanile** [comment]
Closing, as it was solved in a PR
