### ISSUE TITLE
Unnecessary code cleanup and comments

### ISSUE THREAD

**Issue by fcpranav** [ECE444-2020Fall/project1-plateup-group5-pyromaniacs#84]
We used the argon template to bootstrap the project. A lot of unnecessary files are removed. Check the repo for any if extra files to remove and ensure components are properly commented as needed.

AC
- Comments present where needed
- Unnecessary files removed

**Comment by eanile** [comment]
Closing, as no files needed to be deleted and CC is coming up for the project.
